services:
- docker
branches:
  only:
  - master
env:
  global:
  - GCP_PROJECT_ID=terraform-292215
  - IMAGE=gcr.io/terraform-292215/devops-eksamen-1010
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_fe06a949a2b7_key -iv $encrypted_fe06a949a2b7_iv
  -in gkey.json.enc -out gkey.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=gkey.json
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
install: true
script:
- |-
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  set +x
